### ISSUE TITLE
The verifyReceipt endpoint is deprecated

### ISSUE THREAD

**Issue by abdu292** [alexalok/AppleReceiptVerifier.NET#7]
The verifyReceipt endpoint is deprecated.

https://developer.apple.com/documentation/appstorereceipts/verifyreceipt

**Comment by alexalok** [comment]
Thanks, I have reflected this in README.

**Comment by antonio-valentini-ilv** [comment]
Hey @alexalok @abdu292, sorry to reopen this thread. Now that `verifyReceipt` is deprecated, we need to directly call the [get_transaction_info](https://developer.apple.com/documentation/appstoreserverapi/get_transaction_info) endpoint to verify a purchase?

**Comment by alexalok** [comment]
@antonio-valentini-ilv if you have an existing application, I believe you can continue using `verifyReceipt` because I highly doubt Apple would drop its support in the foreseeable future. In new developments I guess it makes sense to use the new APIs from the beginning.

**Comment by antonio-valentini-ilv** [comment]
> @antonio-valentini-ilv if you have an existing application, I believe you can continue using `verifyReceipt` because I highly doubt Apple would drop its support in the foreseeable future. In new developments I guess it makes sense to use the new APIs from the beginning.

Thanks for the info. Do you foresee any update to the `AppleReceiptVerifier.NET` library in the future to support the new APIs?

**Comment by antonio-valentini-ilv** [comment]
> > @antonio-valentini-ilv if you have an existing application, I believe you can continue using `verifyReceipt` because I highly doubt Apple would drop its support in the foreseeable future. In new developments I guess it makes sense to use the new APIs from the beginning.
> 
> Thanks for the info. Do you foresee any update to the `AppleReceiptVerifier.NET` library in the future to support the new APIs?

Sorry, it might sound like a request, but I didn't mean that at all. I'm just interested in knowing if there's any future plan for the library, taking into account eventual help from the community of course 😄

**Comment by alexalok** [comment]
@antonio-valentini-ilv, no worries, it's a totally valid question! Unfortunately, support for the new AppStore Server APIs probably won't come to this library in the foreseeable future. I of course welcome community contributions but personally I am sticking to the `verifyReceipt` for the time being until some specific need arises.

**Comment by antonio-valentini-ilv** [comment]
Got it. Thanks mate. Appreciate the work you've done!
